// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';

var Typer$ReType = require("./Typer.bs.js");

var match = document.querySelector("#root");

if (!(match == null)) {
  Typer$ReType.write("\nThis <span style=\"color:red;\">has red</b> words.", true, (function (eta) {
            return Typer$ReType.write("This text <b>has bold</b> and <i>italic</i> words.", undefined, eta);
          })(Typer$ReType.wait(500, Typer$ReType.write("\nAnd this one is also written on a new line.", true, Typer$ReType.wait(500, Typer$ReType.write("\nThis text is appended to the end of the previous line.", true, Typer$ReType.wait(1000, (function (eta) {
                                    return Typer$ReType.write("And yet another sentence.", undefined, eta);
                                  })(Typer$ReType.wait(2000, (function (eta) {
                                            return Typer$ReType.write("Some more text...", undefined, eta);
                                          })(Typer$ReType.wait(1000, (function (eta) {
                                                    return Typer$ReType.write("This is some test text to use as a demo.", undefined, eta);
                                                  })(Typer$ReType.make(match)))))))))))));
}

/* match Not a pure module */
