// Generated by BUCKLESCRIPT VERSION 5.0.6, PLEASE EDIT WITH CARE
'use strict';


var Animation = /* module */[];

var $$Document = /* module */[];

exports.Animation = Animation;
exports.$$Document = $$Document;
/* No side effect */
